### ISSUE TITLE
Setting up the Database

### ISSUE THREAD

**Issue by mvosborne** [aahvocado/MentorWeb#2]
Creating and populating database tables

**Comment by mvosborne** [comment]
4 hrs

**Comment by mvosborne** [comment]
1 hr 9/25

**Comment by Muffinking** [comment]
3 hrs. Worked on database querying and welcome functionality. (splitting these hours between "Database Setup" and "Login functionality"). 9-26-14

**Comment by mvosborne** [comment]
3 hrs 9/27 Finished making appropriate tables
